// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQSqVJUZc48339iUvz8OHRbD88V3ExZgU',
    appId: '1:1074152454044:web:24959ec919b2fa18507a59',
    messagingSenderId: '1074152454044',
    projectId: 'jobscatalog-e3e93',
    authDomain: 'jobscatalog-e3e93.firebaseapp.com',
    storageBucket: 'jobscatalog-e3e93.firebasestorage.app',
    measurementId: 'G-9FWVNSYQMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjf7eHtJ3-ey2KvAtE0-suMEWOH9GH7qU',
    appId: '1:1074152454044:android:63c20adfdf3e99ff507a59',
    messagingSenderId: '1074152454044',
    projectId: 'jobscatalog-e3e93',
    storageBucket: 'jobscatalog-e3e93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsUTjYPVFcIktGck8BMQXXMtk1939Kt3A',
    appId: '1:1074152454044:ios:52d59e876761ef28507a59',
    messagingSenderId: '1074152454044',
    projectId: 'jobscatalog-e3e93',
    storageBucket: 'jobscatalog-e3e93.firebasestorage.app',
    iosBundleId: 'com.example.jobsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsUTjYPVFcIktGck8BMQXXMtk1939Kt3A',
    appId: '1:1074152454044:ios:52d59e876761ef28507a59',
    messagingSenderId: '1074152454044',
    projectId: 'jobscatalog-e3e93',
    storageBucket: 'jobscatalog-e3e93.firebasestorage.app',
    iosBundleId: 'com.example.jobsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQSqVJUZc48339iUvz8OHRbD88V3ExZgU',
    appId: '1:1074152454044:web:34fac0fd846668c5507a59',
    messagingSenderId: '1074152454044',
    projectId: 'jobscatalog-e3e93',
    authDomain: 'jobscatalog-e3e93.firebaseapp.com',
    storageBucket: 'jobscatalog-e3e93.firebasestorage.app',
    measurementId: 'G-ZJZPMEQVEB',
  );
}
